# Project Identification
# If you do not declare these, SonarQube will pick one for you
sonar.projectKey=[YOUR POJECT KEY HERE]
sonar.projectName=[YOUR PROJECT NAME HERE]

# Server Connection
sonar.host.url=http://127.0.0.1:9001
sonar.token=[YOUR API TOKEN HERE]

# Source Code location (only scan relevant files - for a AFNM mod, that's just ./src )
sonar.sources=src

# Exclusions (Crucial so it doesn't scan your dependencies or build folders)
sonar.exclusions=**/node_modules/**, **/builds/**, **/dist/**, **/scripts/**, **/*.d.ts